import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "./components/header";
import Sidebar from './components/sidebar';
import Grid from "@mui/material/Grid";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Grid container direction="row" spacing={2}>
          <Grid item xs={3}>
            <Sidebar />
          </Grid>
          <Grid item xs={9} id="content">
            {children}
          </Grid>
        </Grid>
      </body>
    </html>
  );
}
//FIXME: 地図の下に黒いスペースができてしまう