name: Deploy to Firebase Hosting on Push(Develop)
on:
  push:
    branches:
      - develop

env:
  SLACK_USERNAME: DeployBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # secretsから.envファイルを作成
      - name: create .env file
        run: |
          cat > .env <<EOF
          TEST=${{ secrets.ENV_DEVELOP }}
          EOF

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: yarn-install
        run: yarn install

      - name: app-build
        run: yarn build

      - name: deploy-to-firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHIMAPO_TEST }}"
          channelId: live
          projectId: shimapo-test
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      # Slack通知
      # 成功
      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_TITLE: Deploy / Success
          SLACK_COLOR: good
          SLACK_MESSAGE: 開発環境へデプロイしました。

      # 失敗
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_TITLE: Deploy / Failure
          SLACK_COLOR: danger
          SLACK_MESSAGE: 開発環境へのデプロイに失敗しました。
